version: "3.9"
services:
  ts-be:
    build:
      context: be
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn api:app --host 0.0.0.0 --port 8874 --reload"
    volumes:
      - "./db:/db"
      - "./be:/app"
    ports:
      - 8874:8874
    environment:
      - TIMESHEET_DB_FILENAME=/db/timesheet.db
  ts-fe:
    build:
      context: ts
      dockerfile: Dockerfile
    environment:
      - HOME=/home/node
    user: "1000:1000"
    command: npm run start
    volumes:
      - "./ts:/app"
    ports:
      - 8875:8875
