name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - "main"

jobs:
  docker-timesheet-web:
    runs-on: ubuntu-latest
    steps:
      - # Checkout the latest code from the repo.
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: web.Dockerfile
          push: false
          tags: zeezdev/timesheet-web:latest
