name: release
run-name: Release

on:
  push:
    branches:
      - main

env:
  PROD_LATEST_TAG: zeezdev/timesheet:latest
  BE_TEST_TAG: zeezdev/timesheet-be:test

jobs:
  docker-timesheet-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build end export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: prod.Dockerfile
          tags: ${{ env.PROD_LATEST_TAG }}
          outputs: type=docker,dest=/tmp/timesheet-prod.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: timesheet-prod-image
          path: /tmp/timesheet-prod.tar
  docker-timesheet-be:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: be
          file: be/Dockerfile
          tags: ${{ env.BE_TEST_TAG }}
          outputs: type=docker,dest=/tmp/timesheet-be.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: timesheet-be-image
          path: /tmp/timesheet-be.tar
  pytest-in-docker:
    runs-on: ubuntu-latest
    needs: docker-timesheet-be
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: timesheet-be-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/timesheet-be.tar
      - name: Run pytest
        run: docker run ${{ env.BE_TEST_TAG }} pytest
  release-prod:
    runs-on: ubuntu-latest
    needs: [pytest-in-docker, docker-timesheet-prod]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: timesheet-prod-image
          path: /tmp
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Load docker image
        run: docker load --input /tmp/timesheet-prod.tar
      - name: Push docker image
        run: docker image push ${{ env.PROD_LATEST_TAG }}
