name: release
run-name: Release

on:
  push:
    branches:
      - main

env:
  PROD_LATEST_TAG: zeezdev/timesheet:latest

jobs:
  test-timesheet-be:
    uses: ./.github/workflows/tests_be_reusable.yml
  test-timesheet-fe:
    uses: ./.github/workflows/tests_fe_reusable.yml
  prod-build:
    uses: ./.github/workflows/build_reusable.yml
    with:
      build_only: false
    secrets: inherit
  release-prod:
    runs-on: ubuntu-latest
    needs: [pytest-in-docker, docker-timesheet-prod]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: timesheet-prod-image
          path: /tmp
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Load docker image
        run: docker load --input /tmp/timesheet-prod.tar
      - name: Push docker image
        run: docker image push ${{ env.PROD_LATEST_TAG }}
