name: tests
run-name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-prod-build:
    uses: ./.github/workflows/build_reusable.yml
    with:
      build_only: true
    secrets: inherit
  test-timesheet-be:
    uses: ./.github/workflows/tests_be_reusable.yml
  test-timesheet-fe:
    uses: ./.github/workflows/tests_fe_reusable.yml
