name: Reusable backend tests

on:
  workflow_call:

env:
  BE_TEST_TAG: zeezdev/timesheet-be:test

jobs:
  docker-timesheet-be:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: be
          file: be/Dockerfile
          tags: ${{ env.BE_TEST_TAG }}
          outputs: type=docker,dest=/tmp/timesheet-be.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: timesheet-be-image
          path: /tmp/timesheet-be.tar
  be-test-in-docker:
    runs-on: ubuntu-latest
    needs: docker-timesheet-be
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: timesheet-be-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/timesheet-be.tar
      - name: Run pytest
        run: docker run ${{ env.BE_TEST_TAG }} pytest
