name: Run tests
run-name: Run test.
on: [push]
#  push:
#    branches:
#      - "main"
#  pull_request:
#    branches:
#      - "main"
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
        # Checkout the latest code from the repo.
      - name: Chackout repo
        uses: actions/checkout@v3
        # Setup which version of Python to use.
      - name: Set Up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
        # Install requirements.
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Run the tests using pytest.
      - name: Run tests
        run: pytest
