name: tests
run-name: Tests

on:
  workflow_call:

env:
  FE_TEST_TAG: zeezdev/timesheet-fe:test

jobs:
  docker-timesheet-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: ts
          file: ts/Dockerfile
          tags: ${{ env.FE_TEST_TAG }}
          outputs: type=docker,dest=/tmp/timesheet-fe.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: timesheet-fe-image
          path: /tmp/timesheet-fe.tar
  fe-test-in-docker:
    runs-on: ubuntu-latest
    needs: docker-timesheet-fe
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: timesheet-fe-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/timesheet-fe.tar
      - name: npm run test-karma
        run: docker run ${{ env.FE_TEST_TAG }} npm run test-karma
