#name: Run tests
#run-name: Run tests
#on:
#  push:
#    branches:
#      - "main"
#  pull_request:
#    branches:
#      - "main"
#jobs:
#  test-backend:
#    runs-on: ubuntu-latest
#    steps:
#        # Checkout the latest code from the repo.
#      - name: Checkout repo
#        uses: actions/checkout@v3
#        # Setup Python.
#      - name: Set Up Python 3.11
#        uses: actions/setup-python@v3
#        with:
#          python-version: 3.11
#        # Install requirements.
#      - name: Install requirements
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r be/requirements.txt
#        # Run the tests using pytest.
#      - name: Run pytest
#        run: |
#          cd be
#          pytest


name: ci
run-name: tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  WEB_TEST_TAG: zeezdev/timesheet-web:test
  BE_TEST_TAG: zeezdev/timesheet-be:test

jobs:
  pytest-in-docker:
    runs-on: ubuntu-latest
#    needs: docker-timesheet-be
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: timesheet-be-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/timesheet-be.tar
      - name: Run pytest
        run: docker run ${{ env.BE_TEST_TAG }} pytest
